### ISSUE TITLE
Want some help with the project?

### ISSUE THREAD

**Issue by BenKennish** [GregoryAM-SP/The-Minecraft-Overviewer#11]
Hi Gregory,

Thanks for taking over the Overviewer project!  I'm very glad I can continue to use Overviewer for my 1.20+ worlds.  I noticed you have little experience of Linux environments but you are a Python dev.  I have a lot of experience with Linux environments but am a PHP dev.  Is there any way that I can help you with the project?

Cheers, Ben

**Comment by BenKennish** [comment]
Oh I just noticed in another issue that you are not a Python developer!  How are you planning to fix bugs or add features to the software as Minecraft evolves?  Cheers

**Comment by JoshuaMarti** [comment]
Howdy Ben!
So, as a preface, I am very clearly not Gregory, but I've been helping him a bit more or less since he started working on Overviewer, and seeing as he is usually free in the evenings, figured I'd pop in real quick, though I'm sure he'll answer tonight.

While you are correct that he wasn't a Python dev, it's been amazing to watch how quickly he's picked things up. I'm a university IT student who learned Python through classes last fall and early this year, and Gregory definitely has a knack for learning things -- all I've really done is help out here and there with debugging and documentation, and give occasional nudges or explanations for code. He's done most of the heavy lifting actually fixing bugs and adding features so far (getting the pitcher plant to render was an adventure for sure).

I am sure he'll answer with specifics for how you can help, but also fairly sure your help is welcome :)

**Comment by Gregory-AM** [comment]
Hey, @BenKennish!
Thank you for creating this issue.

Let me reiterate a bit of what @JoshuaMarti kind of mentioned.
<hr>

While I'm not a Python Developer, I can pick up on languages pretty quickly while looking at the code. Adding in new features that Minecraft has won't be much of a problem, considering I've updated Overviewer from v1.19.9 that didn't support all of Minecraft v1.19 Textures to support literally 98.5% of textures and blocks (minus some missing still).
Creating *Custom Models* is really the only challenge, since they can be a bit tricky (such as the Pitcher Plant).

>Since a lot of the code is already there; copying / pasting is your best friend in this case...😅
Plus, I'm a high-school dropout who just programs for fun. 😁

Typically, I try wrecking my own personal build of Overviewer to locate bugs and apply a patch for them. I do appreciate all help that has come in through Pull Requests, as there are more knowledgeable people out there in the world.
Such as PR #7, where someone added in support for Biome Colors.
Which is something I was trying to figure out for a week before the PR came in.

Also, Josh has been a huge help with updating the README file and testing the new features available on larger Renders.
Which is something I've been trying to get around to do.
<hr>

However, if you're more knowledgeable on Linux Machines / Environments.
You could try to make sure this is correct and works accordingly to the specifications given: [build for linux PR by dalandis](https://github.com/GregoryAM-SP/The-Minecraft-Overviewer/pull/8/commits/00034e8260efc4b326826e732dd77979c1c9b92a).
So that when I add it into the Wiki, it's correct and up-to-date for building on Linux Machines.

If you also have a Discord, you can add me on there: [@]GregoryAM (remove the backets), you should be able to find me as my profile image is the same almost everywhere.

<hr>

I haven't been active for a few days because I've been working my 9 - 5 job and got a bit stressed out. I still have been working on the Wiki and a Graphical User Interface for Overviewer for Windows.

I started learning a new programming language ([Flutter](https://flutter.dev/)) in hopes to also create it for all Operating Systems: Windows, Linux and Mac.

Which I had to use a Tasking App to make sure I'm spending time every day of the week on a new part of the project(s).

**Comment by Gregory-AM** [comment]
Also, If you can think of anything Linux Related that Overviewer needs, can use, or anything. Suggest them! I'm open to any ideas that can help bring Overviewer to more people again. Since there are other programs out there taking OG Overviewer users away.

**Comment by BenKennish** [comment]
Have sent you a friend request on Discord.  Flutter sounds interesting!  Maybe it's just the thing I need to get me excited about development again.

On my Minecraft server, I render a map every night and use hard linking on the Linux filesystem to save space (only files that change from one render to another take up new disk space).  I'd be happy for you to take a look at the bash scripts I use or discuss with me further.  Here's the maps that have been rendered... https://www.tootpolice.org/minecraft/all-maps/hardcore2/

I also made a PHP script that allows you to easily switch between maps while preserving the location you are looking at: https://www.tootpolice.org/minecraft/maps/

Hope life stress reduces soon.

**Comment by BenKennish** [comment]
Oh and the bash script that does the daily render checks whether or not the world has changed in any way since the last render and doesn't run if it hasn't.

**Comment by BenKennish** [comment]
Did you want to look at those bash scripts, @Gregory-AM ?  Would you consider incorporating them into the project for those running Overviewer in a linux environment?

**Comment by Gregory-AM** [comment]
Hey, sorry! I was just clearing out some of the PRs and Issues and forgot about this.
Message me on Discord with a link to them via Google Drive, as it's the only file sharing service I'll accept from.

I haven't had the chance to look into Windows 11 Linux Subsystem. But, If you send them over I'll try my best to install it and test the scripts out.

**Comment by BenKennish** [comment]
Message left on Discord :)
