### ISSUE TITLE
This IS a fork of Minecraft-Overviewer right? How about some credit to the original project?

### ISSUE THREAD

**Issue by dafvid** [GregoryAM-SP/The-Minecraft-Overviewer#16]
Hi
How come you just uploaded the old repo as an initial commit? This repo has history all the way back to 2011 but your "initial commit" was in july this year. I guess you can't fork this now since you've started it already, which by the way is a great initiative, but could you maybe but something in the header to make it more obvious this is NOT you original work?

**Comment by Gregory-AM** [comment]
@dafvid This **is not** a fork.
**This is a clone**.

The original developers stopped working on Overviewer.
Hence the word "Successor" being present on the Repo Page.

The last official update / release to the Overviewer was 2 years ago by the original developers.

Since no one else took over the project, I did. Also, the license Overviewer is under let's me use it's name, assets, and code freely without repercussion and without having to state the original repo.
I do this anyway by mentioning the Docs, and under Getting Help in the readme.

If you'd look under the [commits](https://github.com/GregoryAM-SP/The-Minecraft-Overviewer/commits/main) you'd see the history going back to 2011. It's there. One of the Original developers helped me make sure it was before I fully started working on this.

You can also view the [Forks](https://github.com/overviewer/Minecraft-Overviewer/forks) of the OG Overviewer, you can see that my name is not present. Since **that's not** what this repo is.

Maybe do a bit more digging before coming here and telling me that this repo is trying to be the original, when everyone knows it's not.

My repo is commented on issues in the OG Overviewer as the successor, because that's what it is. I called it the successor before anyone else. It's mentioned in the official Overviewer Discord as the successor, because that's what it is. Because it's the only version that works for the newest version of Minecraft.
