### ISSUE TITLE
Speed regression on resuming incomplete renders

### ISSUE THREAD

**Issue by vilhok** [GregoryAM-SP/The-Minecraft-Overviewer#18]
I killed the process in the middle of the rendering, therefore I now need to re-render. Interestingly, I killed it because the process had become stuck, which might be something else to look into, but I have no further info about that.

It had ONE tile that was not rendered, on the deepest possible zoom level, therefore it was missing one tile from each zoom level.

How ever, the speed of the re-rendering is very slow, just couple of tiles per second.  In previous versions, it used to check the existing tiles very fast, like thousands of tiles per second and find out that the file exists and only render the offending ones. Was there anything changed about this, or is this something on my end?

**Comment by Gregory-AM** [comment]
Sadly, this isn't something new.
Re-rendering a map will always be slower, since it has to check the tiles that were originally rendered.

Which this information can be found somewhere in docs.overviewer.org, where it talks about rendering and re-renders.

---

That being said, there's nothing that can be done about this. I've attempted to speed up the rendering process before, and all attempts have failed. Since it relies on parsing NBT Data, which I can't seem to speed up without it using _way_ more RAM.


You can always check out one of these options:
http://docs.overviewer.org/en/latest/running/?highlight=Rendering#options-1

Since this deals with rendering.

**Comment by Gregory-AM** [comment]
Also, if you want. You can package your world into a zip, upload it to Google Drive, send it over along with your configuration file and I'll take a look at it and see if there are any errors or if I can reproduce the possible hang on a specific tile.
